Dev/d.basalaev/laba1
BaevDaniil/Operating-Systems-labs-2024 pull request #15
Opened 2024-10-25 22:37 UTC by 11AgReS1SoR11

Студент: Басалаев Даниил Александрович
Группа: 5030102/10201
Лабораторная работа №1, вариант 10

2024-12-29 16:40 UTC, AS2 requested changes
Общие замечания:
1) После сборки остается мусор, который не особо нужен. После сборки должен оставаться ТОЛЬКО 1 исполняемый файл. Исправьте это, пожалуйста
2) Вопросы по кодстайлу все в ревью
3) Функционал исправен, однако не работают крайние случаи: когда директория в конфиге описывается строкой не "./some_dir", а " ./some_dir  "
4) При повторном запуске демона правильнее было бы скорее закрывать текущую сессию (или производить перечтение конфига раз уж на то пошло), чем закрывать предыдущую и создавать новую

За создание отдельных скриптов - спасибо! =)

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/main.cpp
> +    if (argc < 2)
Тут должно быть точно два параметра: остальные аргументы в Вашей программе участия не принимают.

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Demon.cpp
> +    if (pid < 0) exit(EXIT_FAILURE);
if (...) exit(...); - не лучшая запись ввиду неудобства дебаггинга. Переписать в несколько строчек.

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Demon.cpp
> +    if (std::ifstream pidFile(PID_FILE); pidFile)
Странная запись, Вы такое часто видите на практике? Лучше вынести объявление и инициализацию переменной отдельно и оставить тут проверку - Вы пишите код для людей

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Demon.hpp
> +    Demon& operator=(Demon const&) = delete;
Добавьте явное удаление перемещающего конструктора и оператора перемещения

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Logger.hpp
> +    Logger(Logger const&) = delete;
Аналогично, как и в синглтоне Демона

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.hpp
> +    Reader(const Reader&) = delete;
Аналогично как и с Логгером

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.cpp
> +        if (auto pathDir1 = std::filesystem::path(dir); pathDir1.is_absolute() && std::filesystem::is_directory(pathDir1))
Разделить на две строки: инициализации и проверки

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.cpp
> +        else if (auto fullPathDir1 = currentDir / pathDir1; std::filesystem::is_directory(fullPathDir1))
Разделить на две строки: инициализации и проверки

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.cpp
> +        if (m_configPath.empty()) { return false; }
В несколько строк написать

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.cpp
> +    if (realpath(path.c_str(), absPath) == nullptr) { return ""; }
Написать в несколько строк

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.cpp
> +    if (!setDir(m_dir1)) { return false; }
В несколько строк написать

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.cpp
> +    if (!setDir(m_dir2)) { return false; }
В несколько строк написать

2024-12-29 16:40 UTC, AS2 commented on Basalaev.Daniil/laba1/Demon/src/Reader.cpp
> +    if (m_interval <= 0) { return false; }
В несколько строк написать

2025-01-03 16:10 UTC, 11AgReS1SoR11 commented on Basalaev.Daniil/laba1/Demon/src/Reader.hpp
> +    Reader(const Reader&) = delete;
Не очень понял замечание, напишите, пожалуйста, подробнее

2025-01-03 16:13 UTC, 11AgReS1SoR11 commented
1. Оставил 2 исполняемых файла, где второй - тесты
4. В задании сказано: "если процесс с таким pid существует, ему должен быть отправлен сигнал SIGTERM" - это значит, что предыдущий нужно убить, разве нет?

2025-02-21 12:39 UTC, merged