Add deleting files by specific depth
BaevDaniil/Operating-Systems-labs-2024 pull request #24
Opened 2024-10-29 17:20 UTC by Ilsaffff

2024-12-29 20:31 UTC, AS2 requested changes
Чуть-чуть поправить код и фулл-балл

2024-12-29 20:31 UTC, AS2 commented on Khamidullin.Ilsaf/lab1/.gitignore
Забавный .gitignore (для виндовских проектов)

2024-12-29 20:31 UTC, AS2 commented on Khamidullin.Ilsaf/lab1/daemon.cpp
> +void deleteDirectoriesByDepth(const std::string& rootPathStr, int depth)
Лучше бы сделать функцию частью класса демона

2024-12-29 20:31 UTC, AS2 commented on Khamidullin.Ilsaf/lab1/daemon.cpp
> +static void handleSignal(int signal)
Аналогичная история

2025-01-04 15:49 UTC, Ilsaffff commented
@AS2, привет! поправил.

2025-02-21 12:32 UTC, merged